# -*- coding: utf-8 -*-
"""pedrapapeltesoura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edPS60LMAULQKnmIN3-z3HFjy-h528Od
"""

import random

opcoes = ["pedra", "papel", "tesoura"]

print("=== JOGO: PEDRA, PAPEL OU TESOURA ===")
print("Digite 'sair' a qualquer momento para encerrar o jogo.\n")

while True:
    jogador = input("Escolha pedra, papel, tesoura ou sair: ").lower().strip()

    if jogador == "sair":
        print("Encerrando o jogo. Obrigado por jogar!")
        break

    if jogador not in opcoes:
        print("Opção inválida. Tente novamente.\n")
        continue

    computador = random.choice(opcoes)

    print(f"Você escolheu: {jogador}")
    print(f"O computador escolheu: {computador}")

    if jogador == computador:
        print("Resultado: Empate!\n")
    elif (
        (jogador == "pedra" and computador == "tesoura") or
        (jogador == "papel" and computador == "pedra") or
        (jogador == "tesoura" and computador == "papel")
    ):
        print("Resultado: Você ganhou!\n")
    else:
        print("Resultado: Você perdeu!\n")